### ISSUE TITLE
QA/PHPcs Issues

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [Makewebbetter/pdf-generator-for-wp#41]
DOC:
https://docs.google.com/document/d/1tUFN4jvwfXr4mKiPZ15ih-gB4hYzSS0UC5LEnvY2p2k/edit?usp=sharing

File:
[pdf-generator-for-wp.zip](https://github.com/Makewebbetter/pdf-generator-for-wp/files/7193662/pdf-generator-for-wp.zip)
[PHPcs.xml.zip](https://github.com/Makewebbetter/pdf-generator-for-wp/files/7193663/PHPcs.xml.zip)

**Comment by vivekkushwaha-cedcoss** [comment]
fixable are fixed and library issues are mentioned in the doc.

**Comment by Sukirti-CEDCOSS** [comment]
Verified
