### ISSUE TITLE
QA Issues

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/pdf-generator-for-wp#48]
**Bug Name -** QA Issues
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 6.1.1
**WordPress Version -** 5.9
**Plugin Version -** 
**Description -**

WC tested up to: 6.1.0 to 6.1.1

There are many places where makewebbetter is used in author or links, kindly search in the global and replace it.

PHPCS Issues-
File is not able to upload here, I send you in DM.

**Comment by pradeepsinghbisht-cedcoss** [comment]
done

**Comment by pradeepsinghbisht-cedcoss** [comment]
phpcs issue will be fixed in future updates

**Comment by AnuraktSachan-CEDCOSS** [comment]
okay
